# Nazwa: Testy - Ręczne Generowanie Artykułów
name: Testy - Ręczne Generowanie Artykułów

on:
  # Pozwala na ręczne uruchomienie workflow z panelu Actions na GitHub
  workflow_dispatch:
    inputs:
      task_to_run:
        description: 'Który artykuł testowy wygenerować?'
        required: true
        default: 'tylkoslask'
        type: choice
        options:
          - tylkoslask
          - tylkoslask2
          - tylkoslask3
          - tylkoslask4
          - all

jobs:
  manual-generate-article:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Pobieranie kodu z repozytorium
        uses: actions/checkout@v4

      - name: 2. Ustawienie środowiska Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 3. Instalacja potrzebnych bibliotek
        run: pip install -r requirements.txt

      - name: Uruchom test dla TylkoSlask.pl
        if: github.event.inputs.task_to_run == 'tylkoslask' || github.event.inputs.task_to_run == 'all'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          TYLKOSLASK_USER: ${{ secrets.TYLKOSLASK_USER }}
          TYLKOSLASK_PASS: ${{ secrets.TYLKOSLASK_PASS }}
          TYLKOSLASK_ER_KEY: ${{ secrets.TYLKOSLASK_ER_KEY }}
        run: python generator.py --site tylkoslask --type news --source Automatycznie

      - name: Uruchom test dla TylkoSlask.pl 2
        if: github.event.inputs.task_to_run == 'tylkoslask2' || github.event.inputs.task_to_run == 'all'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          TYLKOSLASK_USER: ${{ secrets.TYLKOSLASK_USER }}
          TYLKOSLASK_PASS: ${{ secrets.TYLKOSLASK_PASS }}
          TYLKOSLASK_ER_KEY: ${{ secrets.TYLKOSLASK_ER_KEY }}
        run: python generator.py --site tylkoslask2 --type news --source Automatycznie
        
      - name: Uruchom test dla TylkoSlask.pl 3
        if: github.event.inputs.task_to_run == 'tylkoslask3' || github.event.inputs.task_to_run == 'all'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          TYLKOSLASK_USER: ${{ secrets.TYLKOSLASK_USER }}
          TYLKOSLASK_PASS: ${{ secrets.TYLKOSLASK_PASS }}
          TYLKOSLASK_ER_KEY: ${{ secrets.TYLKOSLASK_ER_KEY }}
        run: python generator.py --site tylkoslask3 --type news --source Automatycznie

      - name: Uruchom test dla TylkoSlask.pl 4
        if: github.event.inputs.task_to_run == 'tylkoslask4' || github.event.inputs.task_to_run == 'all'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          TYLKOSLASK_USER: ${{ secrets.TYLKOSLASK_USER }}
          TYLKOSLASK_PASS: ${{ secrets.TYLKOSLASK_PASS }}
          TYLKOSLASK_ER_KEY: ${{ secrets.TYLKOSLASK_ER_KEY }}
        run: python generator.py --site tylkoslask4 --type news --source Automatycznie
