# Nazwa całego procesu, widoczna w panelu Actions
name: Automatyczne Generowanie Artykułów dla TylkoSlask.pl

# Definicja, kiedy proces ma się uruchamiać
on:
  # Pozwala na ręczne uruchomienie workflow z panelu Actions na GitHub (świetne do testów)
  workflow_dispatch:

  # Uruchamia workflow według harmonogramu (czas UTC)
  schedule:
    # Uruchom dla --site tylkoslask co godzinę od 7:00 do 23:00 czasu polskiego (5-21 UTC)
    - cron: '0 5-21 * * *'
    # Uruchom dla --site tylkoslask2 co trzy godziny od 7:00 czasu polskiego (5, 8, 11, 14, 17, 20 UTC)
    - cron: '0 5-21/3 * * *'
    # Uruchom dla --site tylkoslask3 o 10:00, 15:00 i 22:00 czasu polskiego (8, 13, 20 UTC)
    - cron: '0 8,13,20 * * *'
    # Uruchom dla --site tylkoslask4 raz dziennie o 17:00 czasu polskiego (15 UTC)
    - cron: '0 15 * * *'

# Definicja zadań do wykonania
jobs:
  generate-articles:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Pobieranie kodu z repozytorium
        uses: actions/checkout@v4

      - name: 2. Ustawienie środowiska Python
        uses: actions/setup-python@v4
        with:
          # Użyj wersji Pythona, której wymaga Twój projekt
          python-version: '3.11'

      - name: 3. Instalacja potrzebnych bibliotek
        run: pip install -r requirements.txt

      # --- ZADANIA DLA TylkoSlask.pl ---

      - name: Generuj artykuł NEWSOWY dla TylkoSlask.pl (co godzinę 7-23)
        # Uruchom ten krok tylko, jeśli czas z harmonogramu to 'co godzinę od 5 do 21 UTC'
        if: github.event.schedule == '0 5-21 * * *'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          TYLKOSLASK_USER: ${{ secrets.TYLKOSLASK_USER }}
          TYLKOSLASK_PASS: ${{ secrets.TYLKOSLASK_PASS }}
          TYLKOSLASK_ER_KEY: ${{ secrets.TYLKOSLASK_ER_KEY }}
        # Uruchomienie skryptu z odpowiednimi parametrami
        run: python generator.py --site tylkoslask --type news --source Automatycznie

      - name: Generuj artykuł NEWSOWY dla TylkoSlask.pl (co 3 godziny od 7)
        # Uruchom ten krok tylko, jeśli czas z harmonogramu to 'co 3 godziny od 5 UTC'
        if: github.event.schedule == '0 5-21/3 * * *'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          TYLKOSLASK_USER: ${{ secrets.TYLKOSLASK_USER }}
          TYLKOSLASK_PASS: ${{ secrets.TYLKOSLASK_PASS }}
          TYLKOSLASK_ER_KEY: ${{ secrets.TYLKOSLASK_ER_KEY }}
        run: python generator.py --site tylkoslask2 --type news --source Automatycznie
        
      - name: Generuj artykuł NEWSOWY dla TylkoSlask.pl (o 10, 15, 22)
        # Uruchom ten krok tylko, jeśli czas z harmonogramu to '8, 13, 20 UTC'
        if: github.event.schedule == '0 8,13,20 * * *'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          TYLKOSLASK_USER: ${{ secrets.TYLKOSLASK_USER }}
          TYLKOSLASK_PASS: ${{ secrets.TYLKOSLASK_PASS }}
          TYLKOSLASK_ER_KEY: ${{ secrets.TYLKOSLASK_ER_KEY }}
        run: python generator.py --site tylkoslask3 --type news --source Automatycznie

      - name: Generuj artykuł NEWSOWY dla TylkoSlask.pl (raz dziennie o 17)
        # Uruchom ten krok tylko, jeśli czas z harmonogramu to '15 UTC'
        if: github.event.schedule == '0 15 * * *'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          TYLKOSLASK_USER: ${{ secrets.TYLKOSLASK_USER }}
          TYLKOSLASK_PASS: ${{ secrets.TYLKOSLASK_PASS }}
          TYLKOSLASK_ER_KEY: ${{ secrets.TYLKOSLASK_ER_KEY }}
        run: python generator.py --site tylkoslask4 --type news --source Automatycznie
